Expose Compressor Frequency as a sensor
Sammy1Am/mitsubishi-uart pull request #9
Opened 2024-03-14 02:46 UTC by KazWolfe

Base attempt to expose compressor frequency information to Home Assistant. Unfortunately only returns `0` on my unit, so I don't think I can test this fully.

For units that don't support this, it can be disabled with:

```yml
mitsubishi_uart:
  ...
  sensors:
    compressor_frequency:
      name: compressor_frequency
      internal: true
```

(Maybe it'd be better to have some kind of `features` key to allow enabling/disabling features entirely? e.g. vane information for those of us with air handlers?)

2024-03-14 04:37 UTC, Sammy1Am commented
The code for this PR looks good, but I've been a little unsure about implementing this yet:

Frequency (and stage, which did at least return a value for me) are both "known" values, but I don't feel super confident I know what the values actually mean, and haven't been able to really test them myself (I also only ever get 0 for frequency).  I'm not sure, for example, if the frequency value is actually in Hz (it could be half-Hz if the max frequency of the units is below 128, or whatever).  Some of the stages seem to have meaning, but from the reading I'm doing online there's still some speculation about what each one means.

I left them out rather than add sensors with mysterious values, but I can also see the argument for including them just so that people can see what their system is doing and maybe learn what the values mean and bring them back here.

Any thoughts on leaving it out entirely, or maybe having them disabled by default?  Or should we just cram all the info in there :P

2024-03-14 05:05 UTC, KazWolfe commented
I'm always a fan of exposing more information as opposed to less, though point definitely taken about being uncertain about a lot of things. It's going to be one of the issues that plagues the entire CN105/IT Protocol reversing space, regrettably.

I'm basing frequency-as-Hz off of [echavet's project](https://github.com/echavet/MitsubishiCN105ESPHome) as the information seems to be relatively correct, at least for their heat pumps. 

Moving forward, I want to say feature opt-in would be a very good idea here. Until/if we have some way of probing capabilities, users will need to have some sort of way to enable/disable features and reporting. Might be worth borrowing some things from other projects as well - open source and all.

If you'd prefer, I'm also available in the swicago gitter/on discord if faster communication is your style. Given you're the only project that supports MHK2 (a necessity for family approval factor here), I'm vested in trying to make this better.

2024-03-14 07:28 UTC, Sammy1Am requested changes
Still learning about GitHub reviews, hopefully this doesn't come out weird.

Point taken about including as much as possible-- should definitely add "Loop Status" and "Stage" from the `StandbyGetResponsePacket` as well then.

But for anything that's extra detail / not commonly used / not fully understood, let's set `disabled_by_default` so that they don't show up in Home Assistant.

2024-03-14 07:34 UTC, Sammy1Am commented
> If you'd prefer, I'm also available in the swicago gitter/on discord if faster communication is your style. Given you're the only project that supports MHK2 (a necessity for family approval factor here), I'm vested in trying to make this better.

I'm on Discord as sammy1am if you want to message me there.  Finding time to sit down and actually code is hard for me lately, but usually can answer questions / review PRs a little more frequently.  MHK2 was important for family / guest buy-in here as well :)

2024-03-14 15:33 UTC, KazWolfe commented
Derp, don't code without coffee. Change made as requested, didn't know that was a thing! I'll work on adding loop status/state as well, though it does have different names elsewhere... oh boy.

You have requests disabled, so you'll need to shoot me one - I'm `kazwolfe`.

2024-03-14 23:19 UTC, merged

2024-03-14 23:41 UTC, Sammy1Am commented
Made a quick [follow-up commit](https://github.com/Sammy1Am/mitsubishi-uart/commit/a5b79fe5cada2ede2d765a224c711d4880964567) (didn't do it *in* the PR for expediency).  Since the compressor_frequency sensor is already storing the current value, rather than store another copy in the MitsubishiUART class and have to keep them in sync, let's just store it in the sensor.

I also got an error while trying to use `disabled_by_default`.  Did you test that and it's just me, or is there a weird omission from ESPHome for supporting that argument?

2024-03-14 23:47 UTC, KazWolfe commented
Hm. Admittedly I didn’t try a recompile this morning; my bad.

As for compressor frequency, I’m not familiar enough with the codebase here - would that actually trigger an update publish by itself or would we need to wait for another event for that to update? My naïve understanding was that that Boolean controls whether we inform HA.

2024-03-14 23:57 UTC, Sammy1Am commented
> I didn’t try a recompile this morning; my bad.

No worries, I was pretty confident when I gave you the wrong code 🤷‍♂️ .  It's possible to manually add that to the ESPHome config so that option *does* exist (it's in the documentation!), but the Python isn't happy, so we'll have to figure out what's going on there.  A brief search didn't turn up any built-in components using it though.

> that Boolean controls whether we inform HA.

~~This is true for any of the values in the Climate object, but not for additional sensors~~  Oh wait, you're totally right.  I got a bit confused because we're [checking here](https://github.com/Sammy1Am/mitsubishi-uart/blob/a5b79fe5cada2ede2d765a224c711d4880964567/components/mitsubishi_uart/mitsubishi_uart.cpp#L156-L159) to see if the sensor needs to be published.  But actually that line is also behind the boolean, so it would only check the sensor when something else (like the current temperature) changed.  That means temperature source and thermostat temperature are also failing to update right away.

I'll fix that by putting your check back in, and adding checks to the other two.

2024-03-19 04:59 UTC, tjwallace commented
If there is a Discord server/chat I could follow along on please let me know. I'd like to help out if I can. My username is `tjwallace87`.

2024-03-19 05:26 UTC, Sammy1Am commented
There was not, but now there is 😉.
https://discord.gg/ExzZw53U